John 1:14:
  author: John
  audience: Early Christians
  setting: "Written to reveal Jesus as the divine Word made flesh."

Romans 8:28:
  author: Paul
  audience: The Romans
  setting: "Encouraging believers to trust God's plan even in hardship."

Psalm 23:1:
  author: David
  audience: Israel
  setting: "A reflection of God's care and provision."

Proverbs 3:5:
  author: Solomon
  audience: Israelites
  setting: "Encouraging trust in the Lord over personal understanding."

Ephesians 2:8:
  author: Paul
  audience: The Ephesians
  setting: "A reminder that salvation is a gift of grace, not works."